/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MarriageRouteImport } from './routes/marriage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as DonationRouteImport } from './routes/donation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WordQueryRouteImport } from './routes/word.$query'
import { Route as SurahSurahIdRouteImport } from './routes/surah.$surahId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MarriageRoute = MarriageRouteImport.update({
  id: '/marriage',
  path: '/marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRoute = DonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WordQueryRoute = WordQueryRouteImport.update({
  id: '/word/$query',
  path: '/word/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSurahIdRoute = SurahSurahIdRouteImport.update({
  id: '/surah/$surahId',
  path: '/surah/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/community': typeof CommunityRoute
  '/donation': typeof DonationRoute
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
  '/word/$query': typeof WordQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/community': typeof CommunityRoute
  '/donation': typeof DonationRoute
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
  '/word/$query': typeof WordQueryRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/community': typeof CommunityRoute
  '/donation': typeof DonationRoute
  '/hadith': typeof HadithRoute
  '/login': typeof LoginRoute
  '/marriage': typeof MarriageRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
  '/word/$query': typeof WordQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/community'
    | '/donation'
    | '/hadith'
    | '/login'
    | '/marriage'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/posts'
    | '/admin/users'
    | '/blog/$slug'
    | '/surah/$surahId'
    | '/word/$query'
    | '/admin/'
    | '/admin/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/bookmarks'
    | '/community'
    | '/donation'
    | '/hadith'
    | '/login'
    | '/marriage'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/posts'
    | '/admin/users'
    | '/blog/$slug'
    | '/surah/$surahId'
    | '/word/$query'
    | '/admin'
    | '/admin/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/community'
    | '/donation'
    | '/hadith'
    | '/login'
    | '/marriage'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/posts'
    | '/admin/users'
    | '/blog/$slug'
    | '/surah/$surahId'
    | '/word/$query'
    | '/admin/'
    | '/admin/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  CommunityRoute: typeof CommunityRoute
  DonationRoute: typeof DonationRoute
  HadithRoute: typeof HadithRoute
  LoginRoute: typeof LoginRoute
  MarriageRoute: typeof MarriageRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurahSurahIdRoute: typeof SurahSurahIdRoute
  WordQueryRoute: typeof WordQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marriage': {
      id: '/marriage'
      path: '/marriage'
      fullPath: '/marriage'
      preLoaderRoute: typeof MarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/word/$query': {
      id: '/word/$query'
      path: '/word/$query'
      fullPath: '/word/$query'
      preLoaderRoute: typeof WordQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$surahId': {
      id: '/surah/$surahId'
      path: '/surah/$surahId'
      fullPath: '/surah/$surahId'
      preLoaderRoute: typeof SurahSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  CommunityRoute: CommunityRoute,
  DonationRoute: DonationRoute,
  HadithRoute: HadithRoute,
  LoginRoute: LoginRoute,
  MarriageRoute: MarriageRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurahSurahIdRoute: SurahSurahIdRoute,
  WordQueryRoute: WordQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
